name: CI

on:
  pull_request: ~
  push:
    branches:
      - main
  release:
    types:
      - created
  schedule:
    - cron: '43 21 * * *'

jobs:
  test:
    name: "Build and Test - PHP ${{ matrix.php }} Symfony:${{ matrix.symfony-version }} ${{ matrix.deps }}"
    runs-on: ubuntu-latest
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
    strategy:
      matrix:
        include:
          - symfony-version: 5.4
            php: 7.4
          - symfony-version: 6.4
            php: 8.1
          - symfony-version: 7.0
            php: 8.2
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: |
          ./vendor/bin/simple-phpunit

  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: php-cs-fixer

      - name: Run PHP-CS-Fixer
        run:
          php-cs-fixer fix --dry-run --diff
